[book]
title = "Java 25"
description = "Java do zero ao núcleo da linguagem, construindo um sistema completo de terminal."
language = "pt-BR"
src = "src"

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
additional-css = ["theme/modus-vivendi.css"]
git-repository-url = "https://github.com/viniciusdias2902/java_book"
no-section-label = false
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.fold]
enable = true
level = 1

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"
